### ISSUE TITLE
Continuing the simplification effort

### ISSUE THREAD

**Issue by sjcjoosten** [Scott-Crawshaw/Calculus-Solver#7]
In your readme you write:

```
We would like our derivation to not stop when the calculus is complete, but to instead perform the final arithmetic and algebraic steps required to fully complete the derivation. We will hopefully use a package that can perform this arithmetic and algebra for us. It appears the "hint" package can perform the arithmetic.
```

I'm not sure whether the 'hint' package will help you. I suggest writing your own evaluation for the arithmetic steps instead (a function of type Expr -> Expr, or possibly Expr -> (Expr, x) where the x indicates if there was any change (x could be Bool, for instance). Such a function should be a lot more straightforward to write than integrating with other packages.

Furthermore, don't underestimate what you can do by adding laws to LawList.txt.

**Comment by Scott-Crawshaw** [comment]
Thank you for the input!! We will take a self built route rather than trying to find a package.
