### ISSUE TITLE
Potential issue with reasoner

### ISSUE THREAD

**Issue by sjcjoosten** [Scott-Crawshaw/Calculus-Solver#8]
Did you build in anything special to ensure that certain variables can only be replaced if they are constants?

In particular, could you run the following experiment. In LawList.txt, change the order of these two lines:
```
Derivative of Self: deriv x x = 1
Derivative of Constant: deriv x z = 0
```
Then evaluate ``deriv x (x^2)`` (or even just try ``deriv x x``). Does the derivation give the desired result?

(If this works, describe in your readme how it works! If it does not, perhaps you need to fix how the derivative of a negated expression is calculated: try ``deriv x (-x)``.)

**Comment by Scott-Crawshaw** [comment]
We decided to make "z" the variable that can only be replaced by a constant. We implemented this in our match function. Therefore, it works even if the order of the laws is changed. We definitely need to add this to the readme, as people need to know this in order to properly write laws. Thanks!
